### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by ducvui2003** [ducvui2003/android-delivery-react-native#9]
# Các lưu ý:
- Tạo file data chứa data sample, đặt bên trong folder asset/data/promotion
- component chọn promotion có thể tái sử dụng từ componet chọn option trong trang chi tiết sản phẩm
- Tạo type cho obj promotion 
- Không làm trang Get more promotion
![image](https://github.com/user-attachments/assets/c09ed060-8e94-4d2a-9d69-633aaeaba580)

**Comment by Binnguci** [comment]
Nhận thông báo
